// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;

namespace wit_numbers {
    
    public interface INumbersWorld {
        static abstract void TestImports();
        
    }
    
    namespace exports {
        public static class NumbersWorld
        {
            
            [UnmanagedCallersOnly(EntryPoint = "test-imports")]
            public static void wasmExportTestImports() {
                NumbersWorldImpl.TestImports();
            }
        }
    }
    
}
