// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;

namespace wit_numbers.wit.exports.test.numbers.Test;

public interface ITest {
    static abstract byte RoundtripU8(byte a);
    
    static abstract sbyte RoundtripS8(sbyte a);
    
    static abstract ushort RoundtripU16(ushort a);
    
    static abstract short RoundtripS16(short a);
    
    static abstract uint RoundtripU32(uint a);
    
    static abstract int RoundtripS32(int a);
    
    static abstract ulong RoundtripU64(ulong a);
    
    static abstract long RoundtripS64(long a);
    
    static abstract float RoundtripFloat32(float a);
    
    static abstract double RoundtripFloat64(double a);
    
    static abstract uint RoundtripChar(uint a);
    
    static abstract void SetScalar(uint a);
    
    static abstract uint GetScalar();
    
}

