// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;

namespace wit_numbers.wit.exports.test.numbers.Test
{
    public static class TestInterop {
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-u8")]
        public static int wasmExportRoundtripU8(int p0) {
            var ret = TestImpl.RoundtripU8((((byte)p0)));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-u8")]
        public static void cabi_post_wasmExportRoundtripU8(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-u8");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-s8")]
        public static int wasmExportRoundtripS8(int p0) {
            var ret = TestImpl.RoundtripS8((((sbyte)p0)));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-s8")]
        public static void cabi_post_wasmExportRoundtripS8(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-s8");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-u16")]
        public static int wasmExportRoundtripU16(int p0) {
            var ret = TestImpl.RoundtripU16((((ushort)p0)));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-u16")]
        public static void cabi_post_wasmExportRoundtripU16(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-u16");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-s16")]
        public static int wasmExportRoundtripS16(int p0) {
            var ret = TestImpl.RoundtripS16((((short)p0)));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-s16")]
        public static void cabi_post_wasmExportRoundtripS16(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-s16");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-u32")]
        public static int wasmExportRoundtripU32(int p0) {
            var ret = TestImpl.RoundtripU32((unchecked((uint)(p0))));
            return unchecked((int)(ret));
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-u32")]
        public static void cabi_post_wasmExportRoundtripU32(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-u32");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-s32")]
        public static int wasmExportRoundtripS32(int p0) {
            var ret = TestImpl.RoundtripS32((p0));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-s32")]
        public static void cabi_post_wasmExportRoundtripS32(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-s32");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-u64")]
        public static long wasmExportRoundtripU64(long p0) {
            var ret = TestImpl.RoundtripU64((unchecked((ulong)(p0))));
            return unchecked((long)(ret));
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-u64")]
        public static void cabi_post_wasmExportRoundtripU64(long returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-u64");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-s64")]
        public static long wasmExportRoundtripS64(long p0) {
            var ret = TestImpl.RoundtripS64((p0));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-s64")]
        public static void cabi_post_wasmExportRoundtripS64(long returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-s64");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-float32")]
        public static float wasmExportRoundtripFloat32(float p0) {
            var ret = TestImpl.RoundtripFloat32((p0));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-float32")]
        public static void cabi_post_wasmExportRoundtripFloat32(float returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-float32");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-float64")]
        public static double wasmExportRoundtripFloat64(double p0) {
            var ret = TestImpl.RoundtripFloat64((p0));
            return ret;
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-float64")]
        public static void cabi_post_wasmExportRoundtripFloat64(double returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-float64");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-char")]
        public static int wasmExportRoundtripChar(int p0) {
            var ret = TestImpl.RoundtripChar((unchecked((uint)(p0))));
            return ((int)ret);
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#roundtrip-char")]
        public static void cabi_post_wasmExportRoundtripChar(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#roundtrip-char");
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#set-scalar")]
        public static void wasmExportSetScalar(int p0) {
            TestImpl.SetScalar((unchecked((uint)(p0))));
        }
        
        [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#get-scalar")]
        public static int wasmExportGetScalar() {
            var ret = TestImpl.GetScalar();
            return unchecked((int)(ret));
            
        }
        
        [UnmanagedCallersOnly(EntryPoint = "cabi_post_test:numbers/test#get-scalar")]
        public static void cabi_post_wasmExportGetScalar(int returnValue) {
            Console.WriteLine("cabi_post_test:numbers/test#get-scalar");
        }
        
    }
}

